# Generated by Django 5.0.6 on 2024-06-12 18:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("menu", "0002_vote_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="menu",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "created_at"),
                name="one_menu_per_restaurant_per_day_constraint",
            ),
        ),
    ]
